---
- name: Install Nginx
  hosts: managed_nodes
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Check Nginx status
      command: systemctl is-active nginx
      register: result
      changed_when: false

    - name: Show status
      debug:
        msg: "Nginx is {{ result.stdout }}"
