---
- name: Install Nginx
  hosts: managed_nodes
  become: yes

  tasks:

    - name: Update apt
      command: apt update

    - name: Install Nginx
      command: apt install nginx -y

    - name: Start Nginx
      command: systemctl start nginx

    - name: Enable Nginx
      command: systemctl enable nginx

    - name: Check Nginx status
      command: systemctl status nginx
